language: go

go:
- "1.8.x"
- "1.9.x"
- "1.10.x"
- master

before_install:
- go get -t -v ./...

script:
- go test github.com/geekmdio/noted/uuidHelper github.com/geekmdio/noted/logHelper github.com/geekmdio/noted/create -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)