language: go

go:
- "1.10.x"
- master

before_install:
- go get -t -v ./...

script:
- go test -v ./test/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)