package uuidHelper

import (
	"testing"
		"github.com/google/uuid"
)

func TestGenerateGuidStringCanBeParsedAsUuid(t *testing.T) {
	myGuidString := GenerateGuidString()
	_, err := uuid.Parse(myGuidString)
	if err != nil {
		t.Errorf("There was an error processing the guid and it is likely bad: %f", err)
	}
}

func TestGenerateGuidStringWhenParsedReturnsSameValue(t *testing.T) {
	myGuidString := GenerateGuidString()
	uuid, _ := uuid.Parse(myGuidString)
	same := uuid.String() == myGuidString
	if !same {
		t.Errorf("The string generated by the GenerateGuidString function doesn't match that returned by the uuid.Parse function")
	}
}

func TestGenerateGuidThrowingAnError(t *testing.T) {
	myGuidString := XXX_GenerateGuidStringThrowsError()
	uuid, _ := uuid.Parse(myGuidString)
	same := uuid.String() == myGuidString
	if !same {
		t.Errorf("The string generated by the GenerateGuidString function doesn't match that returned by the uuid.Parse function")
	}
}